namespace Loja139;

// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

using WebDriverManager;
using WebDriverManager.DriverConfigs.Impl;

[TestFixture]
public class Teste1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    new DriverManager().SetUpDriver(new ChromeConfig()); 
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
    driver.Manage().Window.Maximize();
  }
  [TearDown]
  protected void TearDown() {
  driver.Quit();
  }


    [Test]

    public void teste1() {
    driver.Navigate().GoToUrl("https://www.saucedemo.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.CssSelector("*[data-test=\"username\"]")).Click();
    driver.FindElement(By.CssSelector("*[data-test=\"username\"]")).SendKeys("standard_user");
    driver.FindElement(By.CssSelector("*[data-test=\"password\"]")).SendKeys("secret_sauce");
    driver.FindElement(By.CssSelector("*[data-test=\"login-button\"]")).Click();
    Assert.That(driver.FindElement(By.CssSelector("#item_4_title_link > .inventory_item_name")).Text, Is.EqualTo("Sauce Labs Backpack"));
    driver.FindElement(By.CssSelector("#item_4_title_link > .inventory_item_name")).Click();
    Assert.That(driver.FindElement(By.CssSelector("*[data-test=\"back-to-products\"]")).Text, Is.EqualTo("Back to products"));
    Assert.That(driver.FindElement(By.CssSelector(".inventory_details_desc")).Text, Is.EqualTo("carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection."));
    IWebElement backButton = driver.FindElement(By.CssSelector("*[data-test=\"back-to-products\"]"));
    Assert.That(backButton.Text, Is.EqualTo("Back to products"));

    var elements = driver.FindElements(By.CssSelector(".inventory_details_img"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".shopping_cart_badge")).Text, Is.EqualTo("1"));
    driver.FindElement(By.CssSelector(".shopping_cart_badge")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".header_secondary_container")).Text, Is.EqualTo("Your Cart"));
    Assert.That(driver.FindElement(By.CssSelector(".cart_quantity")).Text, Is.EqualTo("1"));
    Assert.That(driver.FindElement(By.CssSelector(".inventory_item_name")).Text, Is.EqualTo("Sauce Labs Backpack"));
    Assert.That(driver.FindElement(By.CssSelector("div.inventory_item_price")).Text, Does.Match(@"\$29\.99[\s\S]*Remove"));
    driver.FindElement(By.CssSelector("*[data-test=\"remove-sauce-labs-backpack\"]")).Click();
    driver.Close();
  }

}
